
CREATE TABLE address (

id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

username VARCHAR(50) NOT NULL ,

email VARCHAR(255) NOT NULL,

name VARCHAR(255) NOT NULL,

flat VARCHAR(255) NOT NULL,

street VARCHAR(255) NOT NULL,

state VARCHAR(255) NOT NULL,

phone VARCHAR(255) NOT NULL,

zip INT(6) NOT NULL,

created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

FOREIGN KEY(username) REFERENCES users(username)

);


